### ISSUE TITLE
tg_pytest

### ISSUE THREAD

**Issue by jimtal001** [synthetos/tg_pytest#1]
I am running tg_pytest.py using the setup-no-machine-001.json file and with windows 7/python 3.  It seems to be working now.  Who should I contact to do so?  Is there a forum where tg_pytest is being discussed?

Question: is this code intended for testing scripts only in the case where there is no actual hardware other than the TinyG controller?

**Comment by aldenhart** [comment]
This code is really just a very limited tester, just a few 100 lines of Python. I don't really plan on a any real support for it, and there will not be a forum. I put it out there in case it's useful to people. I only use it on OSX and it's designed for Python 2.7 but I try to use the newer syntax that's compatible with 3.x, but it's not tested on Python 3. So the fact that you got it working on Windows and 3 is nice.

You can write your own JSON to test machines that are not just a controller, at least that's the intent. If you have any test files that you want to contribute please let me know.

**Comment by jimtal001** [comment]
Thank you for the response.
It was necessary to slightly modify the code to get it to run using python 3.4 and I basically hard coded my comport to simplify.  Attached is my python 3.4 code for your review. 

[tg_pytest.py.txt](https://github.com/synthetos/tg_pytest/files/115753/tg_pytest.py.txt)

There is one thing I don't understand in the code and perhaps you can explain.  In the function run_test_file(),  all lines are sent to the tinyG, then immediately all lines are read from the tinyG:

```
for line in send:
    ...        
    s.write(line+'\n'.encode())
    ...

for line in s.readlines():
    ...
```

Assuming I am running a test which requires motion (like your "Tail wag" example) on a real machine, the motion will of course require time to complete.  Therefore I don't understand how the s.readlines() loop is able to wait for the final move complete output from the tinyG.  I hope this question is clear.

**Comment by aldenhart** [comment]
The com port is opened with a 1 second timeout. All send lines are sent, then the read will read all responses and time out after 1 second of inactivity. As long as the board is sending data back (status reports) it will keep reading, waiting to start the 1 second timeout to start.

As it's currently written there is no flow control on the send lines, so they cannot exceed the buffer capacity as noted in the code comments. But it should be possible to enable RTS/CTS flow control on the board and in the serial port open and extend to longer sequences. I have not tested this yet as I have not needed it.

**Comment by jimtal001** [comment]
when I send the following command:

# 
{
    "t":{"label":"Setup status report",
         "send":["{sr:{posx:t,posy:t,posz:t,feed:t,stat:t,homx:t,homy:t,homz:t}}"]},
    "r":{"status":0}
}

I get the following error response:

TEST: Setup full status report
  send: {sr:{posx:t,posy:t,posz:t,feed:t,stat:t,homx:t,homy:t,homz:t}}
  receive: {"er":{"fb":440.20,"st":9,"msg":"File not open"}}
  receive: {"er":{"fb":440.20,"st":9,"msg":"File not open"}}
  receive: {"er":{"fb":440.20,"st":9,"msg":"File not open"}}
  receive: {"er":{"fb":440.20,"st":9,"msg":"File not open"}}
  receive: {"er":{"fb":440.20,"st":9,"msg":"File not open"}}
  receive: {"er":{"fb":440.20,"st":9,"msg":"File not open"}}
  receive: {"er":{"fb":440.20,"st":9,"msg":"File not open"}}
  receive: {"er":{"fb":440.20,"st":9,"msg":"File not open"}}
  receive: {"r":{"sr":{"posx":50.000,"posy":0.000,"posz":0.000,"feed":0.00,"stat":3,"homx":1,"homy":0,"homz":0}},"f":[1,0,63,5064]}
  passed: status: 0, b'{"r":{"sr":{"posx":50.000,"posy":0.000,"posz":0.000,"feed":0.00,"stat":3,"homx":1,"homy":0,"homz":0}},"f":[1,0,63,5064]}'
  EXCEPTION: b'{"er":{"fb":440.20,"st":9,"msg":"File not open"}}'
  EXCEPTION: b'{"er":{"fb":440.20,"st":9,"msg":"File not open"}}'
  EXCEPTION: b'{"er":{"fb":440.20,"st":9,"msg":"File not open"}}'
  EXCEPTION: b'{"er":{"fb":440.20,"st":9,"msg":"File not open"}}'
  EXCEPTION: b'{"er":{"fb":440.20,"st":9,"msg":"File not open"}}'
  EXCEPTION: b'{"er":{"fb":440.20,"st":9,"msg":"File not open"}}'
  EXCEPTION: b'{"er":{"fb":440.20,"st":9,"msg":"File not open"}}'
  EXCEPTION: b'{"er":{"fb":440.20,"st":9,"msg":"File not open"}}'


Any ideal what is incorrect with the status report setup?
Thanks
